artifact_uri: file:c:\Users\loick\Desktop\churn_prediction\models/549845065003665155/c861ac4dce9646eab2a2c7ddf6e0b8a2/artifacts
end_time: 1726938479089
entry_point_name: ''
experiment_id: '549845065003665155'
lifecycle_stage: active
run_id: c861ac4dce9646eab2a2c7ddf6e0b8a2
run_name: XGB_RUS_Normalized
run_uuid: c861ac4dce9646eab2a2c7ddf6e0b8a2
source_name: ''
source_type: 4
source_version: ''
start_time: 1726938466968
status: 3
tags: []
user_id: loick
